### PR TITLE
Bug 1581201 - Increase treeherder-stage size

### PR DESCRIPTION
**Pull request by armenzg**

### CODE REVIEW

**Comment by armenzg** [comment]
@dividehex r?

**Review by dividehex — APPROVED** [review]

**Review by dividehex — CHANGES_REQUESTED** [review]
RDS gp2 storage increases must be at least 10%.  @armenzg should I kick this up to 1100GB instead?

**Comment by armenzg** [comment]
@dividehex sure thanks!

**Comment by armenzg** [comment]
Addressed.

**Review by dividehex — APPROVED** [review]

**Comment by dividehex** [comment]
Landed and applied

**Pull request merged**
